name: Aprendiendo sobre Contextos
run-name: ¡Estoy aprendiendo usar contextos!
on:
  workflow_dispatch:
    inputs:
      github-username:
        description: "Github username"
        required: true
        type: string
      nombre:
        description: "Tu nombre"
        required: true
        default: "Juan"
        type: string
env:
  PROYECTO: "Curso de GitHub Actions"
jobs:
  context-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar variable global
        run: echo "COMPANY=GitHub" >> $GITHUB_ENV
        
      - name: Mostrar contexto de github
        run: |
          echo "Este workflow fue activado por: ${{ github.actor }}"
          echo "Repositorio: ${{ github.repository }}"
          echo "Evento: ${{ github.event_name }}"
          echo "SHA del commit: ${{ github.sha }}"
        env:
          EVENT_TYPE: ${{ github.event_name }}
      
      - name: Comparar input con github.actor
        run: |
          if [ "${{ inputs.username }}" == "${{ github.actor }}" ]; then
            echo "¡El usuario ingresado coincide con el actor!"
          else
            echo "El usuario ingresado no coincide con el actor."
          fi

      - name: Usar el contexto env
        run: echo "El proyecto actual es $PROYECTO"
      
      - name: Usar contexto runner
        run: |
          echo "Sistema operativo del runner: ${{ runner.os }}"
          echo "Espacio disponible: ${{ runner.temp }}"
      
      - name: Usar secrets
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "No se configuró un secreto. Por favor, configúralo antes de ejecutar."
          else
            echo "Secreto recibido: $MY_SECRET"
          fi

      - name: Variables globales (vars)
        run: |
          echo "La compañía es: ${{ vars.COMPANY }}"
          echo "La variable PROYECTO es: $PROYECTO"
      
      - name: Contexto steps
        id: step1
        run: echo "Esto es un paso previo."
      - name: Contexto steps (continuación)
        run: echo "El resultado del paso previo es: ${{ steps.step1.outcome }}"