name: Aprendiendo sobre los Triggers
run-name: ¡Estoy aprendiendo usar diferentes Triggers!
on:
  push:
    branches:
      - aprendiendo-github-actions
  pull_request:
    branches:
      - main
    paths:
      - "**.js"
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
  schedule:
    - cron: "*/10 * * * *" # Cada 10 minutos
  workflow_dispatch: # Este es el trigger que permite ejecutar el workflow manualmente
    inputs:
      mensaje:
        description: "Mensaje personalizado para enviar"
        required: true
        default: "¡Hola!"

jobs:
  triggers-job:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar información del trigger
        run: |
          echo "Este workflow fue activado por: ${{ github.event_name }}"

      - name: Mostrar tiempo actual
        run: |
          echo "Este workflow se ejecutó a las: $(date)"

      - name: Información adicional para issues
        if: ${{ github.event_name == 'issues' }}
        run: |
          echo "El issue tiene el siguiente título: ${{ github.event.issue.title }}"
          echo "La acción realizada fue: ${{ github.event.action }}"

      - name: Detalles del comentario
        if: ${{ github.event_name == 'issue_comment' }}
        run: |
          echo "El comentario fue: ${{ github.event.comment.body }}"
          echo "La acción realizada en el comentario fue: ${{ github.event.action }}"
          echo "El comentario pertenece al issue/pull request: #${{ github.event.issue.number }}"
          echo "El comentario fue realizado por: ${{ github.event.comment.user.login }}"

      - name: Mostrar mensaje personalizado desde workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "El mensaje personalizado es: ${{ github.event.inputs.mensaje }}"
